### ISSUE TITLE
CSRF error upon selecting existing project and creating new project

### ISSUE THREAD

**Issue by jameshofstra** [JoeDevelops/362Project#1]
After user login if existing projects is selected, and then a new project is created, a CSRF error occurs.

**Comment by JoeDevelops** [comment]
This issue only arises when:
(1) At the welcome screen 'existing projects' is selected.
(2) The user has no existing projects, so is redirected to 'create projects' page which displays the error message "You need to create a project first"
(3) Create project is selected

I'm guessing this is due to the way the person is routed to the page.  Maybe they are coming from a place where the csrf update is not applied before the redirect

**Comment by JoeDevelops** [comment]
After I wrote this response, I realized what was wrong. 
This language was used in updating the csrf and rendering to response.  The projects_error part is just another dictionary entry which is passed with the render.  Values must be in dict to be used in template FYI
        c = {}
        c.update(csrf(request))
        c.update({'no_projects_error':1})
	return render_to_response('create_project.html', c)
